// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYnLpKWl-vNe_rqGpBIkaHzzNW-1Q21-k',
    appId: '1:555356454569:web:7a8aa09d05bf34d94073b8',
    messagingSenderId: '555356454569',
    projectId: 'elomda-96ae3',
    authDomain: 'elomda-96ae3.firebaseapp.com',
    storageBucket: 'elomda-96ae3.appspot.com',
    measurementId: 'G-C88L0DR9Z9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFY862kjR5_jAhJmS4vXHRbwAibNArqTw',
    appId: '1:555356454569:android:92ebc22ae255895f4073b8',
    messagingSenderId: '555356454569',
    projectId: 'elomda-96ae3',
    storageBucket: 'elomda-96ae3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCrepZ5BwUzvq5ml12TcfuEW1UVyAS5aY',
    appId: '1:555356454569:ios:7bdd00429c18ede54073b8',
    messagingSenderId: '555356454569',
    projectId: 'elomda-96ae3',
    storageBucket: 'elomda-96ae3.appspot.com',
    iosBundleId: 'com.topbusiness.khadamat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCrepZ5BwUzvq5ml12TcfuEW1UVyAS5aY',
    appId: '1:555356454569:ios:7bdd00429c18ede54073b8',
    messagingSenderId: '555356454569',
    projectId: 'elomda-96ae3',
    storageBucket: 'elomda-96ae3.appspot.com',
    iosBundleId: 'com.topbusiness.khadamat',
  );
}
